name: TileEdit
main: com.github.caoli5288.tileedit.TileEdit
version: 1.0

commands:
  tileedit:
    permission: tileedit.use
    usage: |
      tileedit save [LOADED|BORDER|WE] [TYPE...]
      tileedit load <filename>
      tileedit select <level_name>

softdepend: [WorldEdit]